### ISSUE TITLE
Añadir en HTML salida del buscador de commonscat

### ISSUE THREAD

**Issue by dennistobar** [lahire/wiki-imagefinder#12]
Hay que añadir dentro del HTML una salida al script `commonscat.py` para que se pueda descargar como un csv, al igual que la versión de imágenes.

No sé si seguir teniendo el enlace simbólico o crear un `.conf` (o `.env`) que nos indique en qué ruta hay que generar el archivo de salida.

**Comment by lahire** [comment]
No estaría mal ya armar un config file con outputs, me voy a poner con eso

**Comment by lahire** [comment]
Check https://github.com/lahire/wiki-imagefinder/tree/html_print

**Comment by dennistobar** [comment]
Veamos si con el #20 podemos cerrar este hilo :)
