### ISSUE TITLE
Dar una mano con #1bib1ref

### ISSUE THREAD

**Issue by lahire** [lahire/wiki-imagefinder#17]
Habría que modificar el script para que busque artículos con ese hashtags (porque el hashtags app no anda)
y mostrarlo en html

----

**Comment by dennistobar** [comment]
Tengo un script en toolforge que puede buscar el string en es.wikipedia... tu me dices si lo configuro para que funcione(?)

**Comment by lahire** [comment]
Me topé con esto porque Mauri Genta me contó que están teniendo problemas con la herramienta de los hashtags. Pensé en ver que tag buscar y armarles un csv o algo así...ahora que veo igual la herramienta ya volvió a funcionar
