### ISSUE TITLE
Error de Q

### ISSUE THREAD

**Issue by dennistobar** [lahire/wiki-imagefinder#22]
[[es:Abjasia]] has no Q element.
Traceback (most recent call last):
File "./commonscat.py", line 55, in 
main()
File "./commonscat.py", line 51, in main
work(pages)
File "./commonscat.py", line 25, in work
printToCsv(line=[page.full_url(),getQ(page).full_url(),page.title(),category], archivo='hasno.csv')
AttributeError: 'NoneType' object has no attribute 'full_url'
<class 'AttributeError'>
CRITICAL: Closing network session.

Pull a lo nuevo y fijate, no se que onda esto

----
Me parece que Abjasia efectivamente no tiene un elemento de Wikidata asociado....

**Comment by lahire** [comment]
e igual lo pasa. Que podrá ser?

**Comment by dennistobar** [comment]
Creo que en #21 lo resuelvo, ya que fue un error involuntario...
